// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: mesh_proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentHeartbeat struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AgentId           string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Address           string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Status            string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	IntelligenceLevel int32                  `protobuf:"varint,4,opt,name=intelligence_level,json=intelligenceLevel,proto3" json:"intelligence_level,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AgentHeartbeat) Reset() {
	*x = AgentHeartbeat{}
	mi := &file_mesh_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHeartbeat) ProtoMessage() {}

func (x *AgentHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHeartbeat.ProtoReflect.Descriptor instead.
func (*AgentHeartbeat) Descriptor() ([]byte, []int) {
	return file_mesh_proto_proto_rawDescGZIP(), []int{0}
}

func (x *AgentHeartbeat) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentHeartbeat) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AgentHeartbeat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentHeartbeat) GetIntelligenceLevel() int32 {
	if x != nil {
		return x.IntelligenceLevel
	}
	return 0
}

type StateUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Progress      float64                `protobuf:"fixed64,2,opt,name=progress,proto3" json:"progress,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateUpdate) Reset() {
	*x = StateUpdate{}
	mi := &file_mesh_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateUpdate) ProtoMessage() {}

func (x *StateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateUpdate.ProtoReflect.Descriptor instead.
func (*StateUpdate) Descriptor() ([]byte, []int) {
	return file_mesh_proto_proto_rawDescGZIP(), []int{1}
}

func (x *StateUpdate) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StateUpdate) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *StateUpdate) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type TaskLease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLease) Reset() {
	*x = TaskLease{}
	mi := &file_mesh_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLease) ProtoMessage() {}

func (x *TaskLease) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLease.ProtoReflect.Descriptor instead.
func (*TaskLease) Descriptor() ([]byte, []int) {
	return file_mesh_proto_proto_rawDescGZIP(), []int{2}
}

func (x *TaskLease) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type TaskAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_mesh_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_mesh_proto_proto_rawDescGZIP(), []int{3}
}

func (x *TaskAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAssignment) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_mesh_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_mesh_proto_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletRequest) Reset() {
	*x = WalletRequest{}
	mi := &file_mesh_proto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletRequest) ProtoMessage() {}

func (x *WalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletRequest.ProtoReflect.Descriptor instead.
func (*WalletRequest) Descriptor() ([]byte, []int) {
	return file_mesh_proto_proto_rawDescGZIP(), []int{5}
}

func (x *WalletRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type WalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       float64                `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Staked        float64                `protobuf:"fixed64,2,opt,name=staked,proto3" json:"staked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletResponse) Reset() {
	*x = WalletResponse{}
	mi := &file_mesh_proto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletResponse) ProtoMessage() {}

func (x *WalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletResponse.ProtoReflect.Descriptor instead.
func (*WalletResponse) Descriptor() ([]byte, []int) {
	return file_mesh_proto_proto_rawDescGZIP(), []int{6}
}

func (x *WalletResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *WalletResponse) GetStaked() float64 {
	if x != nil {
		return x.Staked
	}
	return 0
}

type StakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StakeRequest) Reset() {
	*x = StakeRequest{}
	mi := &file_mesh_proto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StakeRequest) ProtoMessage() {}

func (x *StakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StakeRequest.ProtoReflect.Descriptor instead.
func (*StakeRequest) Descriptor() ([]byte, []int) {
	return file_mesh_proto_proto_rawDescGZIP(), []int{7}
}

func (x *StakeRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StakeRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_mesh_proto_proto protoreflect.FileDescriptor

const file_mesh_proto_proto_rawDesc = "" +
	"\n" +
	"\x10mesh_proto.proto\x12\x05proto\"\x8c\x01\n" +
	"\x0eAgentHeartbeat\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12-\n" +
	"\x12intelligence_level\x18\x04 \x01(\x05R\x11intelligenceLevel\"\\\n" +
	"\vStateUpdate\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x01R\bprogress\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\"&\n" +
	"\tTaskLease\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"K\n" +
	"\x0eTaskAssignment\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\">\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"*\n" +
	"\rWalletRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"B\n" +
	"\x0eWalletResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x01R\abalance\x12\x16\n" +
	"\x06staked\x18\x02 \x01(\x01R\x06staked\"A\n" +
	"\fStakeRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount2\x9c\x02\n" +
	"\rSovereignMesh\x123\n" +
	"\tHeartbeat\x12\x15.proto.AgentHeartbeat\x1a\x0f.proto.Response\x120\n" +
	"\tSyncState\x12\x12.proto.StateUpdate\x1a\x0f.proto.Response\x126\n" +
	"\vRequestTask\x12\x10.proto.TaskLease\x1a\x15.proto.TaskAssignment\x129\n" +
	"\n" +
	"GetBalance\x12\x14.proto.WalletRequest\x1a\x15.proto.WalletResponse\x121\n" +
	"\tStakeCoin\x12\x13.proto.StakeRequest\x1a\x0f.proto.ResponseB*Z(github.com/pqr-info/sovereign-mesh/protob\x06proto3"

var (
	file_mesh_proto_proto_rawDescOnce sync.Once
	file_mesh_proto_proto_rawDescData []byte
)

func file_mesh_proto_proto_rawDescGZIP() []byte {
	file_mesh_proto_proto_rawDescOnce.Do(func() {
		file_mesh_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mesh_proto_proto_rawDesc), len(file_mesh_proto_proto_rawDesc)))
	})
	return file_mesh_proto_proto_rawDescData
}

var file_mesh_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_mesh_proto_proto_goTypes = []any{
	(*AgentHeartbeat)(nil), // 0: proto.AgentHeartbeat
	(*StateUpdate)(nil),    // 1: proto.StateUpdate
	(*TaskLease)(nil),      // 2: proto.TaskLease
	(*TaskAssignment)(nil), // 3: proto.TaskAssignment
	(*Response)(nil),       // 4: proto.Response
	(*WalletRequest)(nil),  // 5: proto.WalletRequest
	(*WalletResponse)(nil), // 6: proto.WalletResponse
	(*StakeRequest)(nil),   // 7: proto.StakeRequest
}
var file_mesh_proto_proto_depIdxs = []int32{
	0, // 0: proto.SovereignMesh.Heartbeat:input_type -> proto.AgentHeartbeat
	1, // 1: proto.SovereignMesh.SyncState:input_type -> proto.StateUpdate
	2, // 2: proto.SovereignMesh.RequestTask:input_type -> proto.TaskLease
	5, // 3: proto.SovereignMesh.GetBalance:input_type -> proto.WalletRequest
	7, // 4: proto.SovereignMesh.StakeCoin:input_type -> proto.StakeRequest
	4, // 5: proto.SovereignMesh.Heartbeat:output_type -> proto.Response
	4, // 6: proto.SovereignMesh.SyncState:output_type -> proto.Response
	3, // 7: proto.SovereignMesh.RequestTask:output_type -> proto.TaskAssignment
	6, // 8: proto.SovereignMesh.GetBalance:output_type -> proto.WalletResponse
	4, // 9: proto.SovereignMesh.StakeCoin:output_type -> proto.Response
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mesh_proto_proto_init() }
func file_mesh_proto_proto_init() {
	if File_mesh_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mesh_proto_proto_rawDesc), len(file_mesh_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mesh_proto_proto_goTypes,
		DependencyIndexes: file_mesh_proto_proto_depIdxs,
		MessageInfos:      file_mesh_proto_proto_msgTypes,
	}.Build()
	File_mesh_proto_proto = out.File
	file_mesh_proto_proto_goTypes = nil
	file_mesh_proto_proto_depIdxs = nil
}
