// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: mesh_proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SovereignMesh_Heartbeat_FullMethodName   = "/proto.SovereignMesh/Heartbeat"
	SovereignMesh_SyncState_FullMethodName   = "/proto.SovereignMesh/SyncState"
	SovereignMesh_RequestTask_FullMethodName = "/proto.SovereignMesh/RequestTask"
	SovereignMesh_GetBalance_FullMethodName  = "/proto.SovereignMesh/GetBalance"
	SovereignMesh_StakeCoin_FullMethodName   = "/proto.SovereignMesh/StakeCoin"
)

// SovereignMeshClient is the client API for SovereignMesh service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SovereignMeshClient interface {
	// Agents register their presence and status
	Heartbeat(ctx context.Context, in *AgentHeartbeat, opts ...grpc.CallOption) (*Response, error)
	// Remote state synchronization (Proxy for memory bus)
	SyncState(ctx context.Context, in *StateUpdate, opts ...grpc.CallOption) (*Response, error)
	// Orchestration: Agents pull tasks from the controller
	RequestTask(ctx context.Context, in *TaskLease, opts ...grpc.CallOption) (*TaskAssignment, error)
	// Cobalt Chrome Wallet API
	GetBalance(ctx context.Context, in *WalletRequest, opts ...grpc.CallOption) (*WalletResponse, error)
	StakeCoin(ctx context.Context, in *StakeRequest, opts ...grpc.CallOption) (*Response, error)
}

type sovereignMeshClient struct {
	cc grpc.ClientConnInterface
}

func NewSovereignMeshClient(cc grpc.ClientConnInterface) SovereignMeshClient {
	return &sovereignMeshClient{cc}
}

func (c *sovereignMeshClient) Heartbeat(ctx context.Context, in *AgentHeartbeat, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, SovereignMesh_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignMeshClient) SyncState(ctx context.Context, in *StateUpdate, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, SovereignMesh_SyncState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignMeshClient) RequestTask(ctx context.Context, in *TaskLease, opts ...grpc.CallOption) (*TaskAssignment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskAssignment)
	err := c.cc.Invoke(ctx, SovereignMesh_RequestTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignMeshClient) GetBalance(ctx context.Context, in *WalletRequest, opts ...grpc.CallOption) (*WalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletResponse)
	err := c.cc.Invoke(ctx, SovereignMesh_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sovereignMeshClient) StakeCoin(ctx context.Context, in *StakeRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, SovereignMesh_StakeCoin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SovereignMeshServer is the server API for SovereignMesh service.
// All implementations must embed UnimplementedSovereignMeshServer
// for forward compatibility.
type SovereignMeshServer interface {
	// Agents register their presence and status
	Heartbeat(context.Context, *AgentHeartbeat) (*Response, error)
	// Remote state synchronization (Proxy for memory bus)
	SyncState(context.Context, *StateUpdate) (*Response, error)
	// Orchestration: Agents pull tasks from the controller
	RequestTask(context.Context, *TaskLease) (*TaskAssignment, error)
	// Cobalt Chrome Wallet API
	GetBalance(context.Context, *WalletRequest) (*WalletResponse, error)
	StakeCoin(context.Context, *StakeRequest) (*Response, error)
	mustEmbedUnimplementedSovereignMeshServer()
}

// UnimplementedSovereignMeshServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSovereignMeshServer struct{}

func (UnimplementedSovereignMeshServer) Heartbeat(context.Context, *AgentHeartbeat) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedSovereignMeshServer) SyncState(context.Context, *StateUpdate) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncState not implemented")
}
func (UnimplementedSovereignMeshServer) RequestTask(context.Context, *TaskLease) (*TaskAssignment, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestTask not implemented")
}
func (UnimplementedSovereignMeshServer) GetBalance(context.Context, *WalletRequest) (*WalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedSovereignMeshServer) StakeCoin(context.Context, *StakeRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method StakeCoin not implemented")
}
func (UnimplementedSovereignMeshServer) mustEmbedUnimplementedSovereignMeshServer() {}
func (UnimplementedSovereignMeshServer) testEmbeddedByValue()                       {}

// UnsafeSovereignMeshServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SovereignMeshServer will
// result in compilation errors.
type UnsafeSovereignMeshServer interface {
	mustEmbedUnimplementedSovereignMeshServer()
}

func RegisterSovereignMeshServer(s grpc.ServiceRegistrar, srv SovereignMeshServer) {
	// If the following call panics, it indicates UnimplementedSovereignMeshServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SovereignMesh_ServiceDesc, srv)
}

func _SovereignMesh_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentHeartbeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignMeshServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignMesh_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignMeshServer).Heartbeat(ctx, req.(*AgentHeartbeat))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignMesh_SyncState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignMeshServer).SyncState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignMesh_SyncState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignMeshServer).SyncState(ctx, req.(*StateUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignMesh_RequestTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskLease)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignMeshServer).RequestTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignMesh_RequestTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignMeshServer).RequestTask(ctx, req.(*TaskLease))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignMesh_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignMeshServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignMesh_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignMeshServer).GetBalance(ctx, req.(*WalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SovereignMesh_StakeCoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SovereignMeshServer).StakeCoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SovereignMesh_StakeCoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SovereignMeshServer).StakeCoin(ctx, req.(*StakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SovereignMesh_ServiceDesc is the grpc.ServiceDesc for SovereignMesh service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SovereignMesh_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SovereignMesh",
	HandlerType: (*SovereignMeshServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _SovereignMesh_Heartbeat_Handler,
		},
		{
			MethodName: "SyncState",
			Handler:    _SovereignMesh_SyncState_Handler,
		},
		{
			MethodName: "RequestTask",
			Handler:    _SovereignMesh_RequestTask_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _SovereignMesh_GetBalance_Handler,
		},
		{
			MethodName: "StakeCoin",
			Handler:    _SovereignMesh_StakeCoin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mesh_proto.proto",
}
