# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sync_pb2 as sync__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sync_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentSyncStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/sovereign.AgentSync/Ping',
                request_serializer=sync__pb2.PingRequest.SerializeToString,
                response_deserializer=sync__pb2.PingResponse.FromString,
                _registered_method=True)
        self.SyncState = channel.unary_unary(
                '/sovereign.AgentSync/SyncState',
                request_serializer=sync__pb2.StatePayload.SerializeToString,
                response_deserializer=sync__pb2.SyncAck.FromString,
                _registered_method=True)
        self.StreamInference = channel.unary_stream(
                '/sovereign.AgentSync/StreamInference',
                request_serializer=sync__pb2.InferenceRequest.SerializeToString,
                response_deserializer=sync__pb2.InferenceChunk.FromString,
                _registered_method=True)
        self.RemoteExecute = channel.unary_unary(
                '/sovereign.AgentSync/RemoteExecute',
                request_serializer=sync__pb2.CommandPayload.SerializeToString,
                response_deserializer=sync__pb2.CommandResult.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/sovereign.AgentSync/CreateUser',
                request_serializer=sync__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=sync__pb2.UserResponse.FromString,
                _registered_method=True)
        self.ChangePassword = channel.unary_unary(
                '/sovereign.AgentSync/ChangePassword',
                request_serializer=sync__pb2.ChangePasswordRequest.SerializeToString,
                response_deserializer=sync__pb2.UserResponse.FromString,
                _registered_method=True)
        self.ManageGroup = channel.unary_unary(
                '/sovereign.AgentSync/ManageGroup',
                request_serializer=sync__pb2.ManageGroupRequest.SerializeToString,
                response_deserializer=sync__pb2.UserResponse.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/sovereign.AgentSync/ListUsers',
                request_serializer=sync__pb2.UserDirectoryRequest.SerializeToString,
                response_deserializer=sync__pb2.UserDirectoryResponse.FromString,
                _registered_method=True)
        self.SyncUsers = channel.unary_unary(
                '/sovereign.AgentSync/SyncUsers',
                request_serializer=sync__pb2.SyncUsersRequest.SerializeToString,
                response_deserializer=sync__pb2.UserResponse.FromString,
                _registered_method=True)
        self.GetProcessDirectory = channel.unary_unary(
                '/sovereign.AgentSync/GetProcessDirectory',
                request_serializer=sync__pb2.ProcessDirectoryRequest.SerializeToString,
                response_deserializer=sync__pb2.ProcessDirectoryResponse.FromString,
                _registered_method=True)
        self.GetPortBindings = channel.unary_unary(
                '/sovereign.AgentSync/GetPortBindings',
                request_serializer=sync__pb2.PortBindingsRequest.SerializeToString,
                response_deserializer=sync__pb2.PortBindingsResponse.FromString,
                _registered_method=True)
        self.TeleportAgent = channel.unary_unary(
                '/sovereign.AgentSync/TeleportAgent',
                request_serializer=sync__pb2.TeleportRequest.SerializeToString,
                response_deserializer=sync__pb2.TeleportResponse.FromString,
                _registered_method=True)
        self.TracePedigree = channel.unary_unary(
                '/sovereign.AgentSync/TracePedigree',
                request_serializer=sync__pb2.PedigreeRequest.SerializeToString,
                response_deserializer=sync__pb2.PedigreeResponse.FromString,
                _registered_method=True)
        self.ProposeSwarmMutation = channel.unary_unary(
                '/sovereign.AgentSync/ProposeSwarmMutation',
                request_serializer=sync__pb2.MutationRequest.SerializeToString,
                response_deserializer=sync__pb2.MutationResponse.FromString,
                _registered_method=True)
        self.QuerySwarmLedger = channel.unary_unary(
                '/sovereign.AgentSync/QuerySwarmLedger',
                request_serializer=sync__pb2.LedgerQueryRequest.SerializeToString,
                response_deserializer=sync__pb2.LedgerQueryResponse.FromString,
                _registered_method=True)
        self.TimeTravelOverride = channel.unary_unary(
                '/sovereign.AgentSync/TimeTravelOverride',
                request_serializer=sync__pb2.TimeTravelRequest.SerializeToString,
                response_deserializer=sync__pb2.TimeTravelResponse.FromString,
                _registered_method=True)
        self.ForensicAudit = channel.unary_unary(
                '/sovereign.AgentSync/ForensicAudit',
                request_serializer=sync__pb2.ForensicRequest.SerializeToString,
                response_deserializer=sync__pb2.ForensicResponse.FromString,
                _registered_method=True)


class AgentSyncServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamInference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoteExecute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """User Maintenance & Synchronization RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangePassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ManageGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcessDirectory(self, request, context):
        """Process & Port Monitoring RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPortBindings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TeleportAgent(self, request, context):
        """High-Speed Agent Migration (Virtual Travel) RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TracePedigree(self, request, context):
        """Agent Pedigree & 7-Layer Swarm Cooperation RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProposeSwarmMutation(self, request, context):
        """Agent Ticketing, Relational Memory, and Immutable Ledger RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuerySwarmLedger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TimeTravelOverride(self, request, context):
        """Jetweb Time Machine & Forensic Decision Accounting RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForensicAudit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentSyncServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=sync__pb2.PingRequest.FromString,
                    response_serializer=sync__pb2.PingResponse.SerializeToString,
            ),
            'SyncState': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncState,
                    request_deserializer=sync__pb2.StatePayload.FromString,
                    response_serializer=sync__pb2.SyncAck.SerializeToString,
            ),
            'StreamInference': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamInference,
                    request_deserializer=sync__pb2.InferenceRequest.FromString,
                    response_serializer=sync__pb2.InferenceChunk.SerializeToString,
            ),
            'RemoteExecute': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoteExecute,
                    request_deserializer=sync__pb2.CommandPayload.FromString,
                    response_serializer=sync__pb2.CommandResult.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=sync__pb2.CreateUserRequest.FromString,
                    response_serializer=sync__pb2.UserResponse.SerializeToString,
            ),
            'ChangePassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangePassword,
                    request_deserializer=sync__pb2.ChangePasswordRequest.FromString,
                    response_serializer=sync__pb2.UserResponse.SerializeToString,
            ),
            'ManageGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.ManageGroup,
                    request_deserializer=sync__pb2.ManageGroupRequest.FromString,
                    response_serializer=sync__pb2.UserResponse.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=sync__pb2.UserDirectoryRequest.FromString,
                    response_serializer=sync__pb2.UserDirectoryResponse.SerializeToString,
            ),
            'SyncUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncUsers,
                    request_deserializer=sync__pb2.SyncUsersRequest.FromString,
                    response_serializer=sync__pb2.UserResponse.SerializeToString,
            ),
            'GetProcessDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcessDirectory,
                    request_deserializer=sync__pb2.ProcessDirectoryRequest.FromString,
                    response_serializer=sync__pb2.ProcessDirectoryResponse.SerializeToString,
            ),
            'GetPortBindings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPortBindings,
                    request_deserializer=sync__pb2.PortBindingsRequest.FromString,
                    response_serializer=sync__pb2.PortBindingsResponse.SerializeToString,
            ),
            'TeleportAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.TeleportAgent,
                    request_deserializer=sync__pb2.TeleportRequest.FromString,
                    response_serializer=sync__pb2.TeleportResponse.SerializeToString,
            ),
            'TracePedigree': grpc.unary_unary_rpc_method_handler(
                    servicer.TracePedigree,
                    request_deserializer=sync__pb2.PedigreeRequest.FromString,
                    response_serializer=sync__pb2.PedigreeResponse.SerializeToString,
            ),
            'ProposeSwarmMutation': grpc.unary_unary_rpc_method_handler(
                    servicer.ProposeSwarmMutation,
                    request_deserializer=sync__pb2.MutationRequest.FromString,
                    response_serializer=sync__pb2.MutationResponse.SerializeToString,
            ),
            'QuerySwarmLedger': grpc.unary_unary_rpc_method_handler(
                    servicer.QuerySwarmLedger,
                    request_deserializer=sync__pb2.LedgerQueryRequest.FromString,
                    response_serializer=sync__pb2.LedgerQueryResponse.SerializeToString,
            ),
            'TimeTravelOverride': grpc.unary_unary_rpc_method_handler(
                    servicer.TimeTravelOverride,
                    request_deserializer=sync__pb2.TimeTravelRequest.FromString,
                    response_serializer=sync__pb2.TimeTravelResponse.SerializeToString,
            ),
            'ForensicAudit': grpc.unary_unary_rpc_method_handler(
                    servicer.ForensicAudit,
                    request_deserializer=sync__pb2.ForensicRequest.FromString,
                    response_serializer=sync__pb2.ForensicResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sovereign.AgentSync', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sovereign.AgentSync', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentSync(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sovereign.AgentSync/Ping',
            sync__pb2.PingRequest.SerializeToString,
            sync__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sovereign.AgentSync/SyncState',
            sync__pb2.StatePayload.SerializeToString,
            sync__pb2.SyncAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sovereign.AgentSync/StreamInference',
            sync__pb2.InferenceRequest.SerializeToString,
            sync__pb2.InferenceChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoteExecute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sovereign.AgentSync/RemoteExecute',
            sync__pb2.CommandPayload.SerializeToString,
            sync__pb2.CommandResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sovereign.AgentSync/CreateUser',
            sync__pb2.CreateUserRequest.SerializeToString,
            sync__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangePassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sovereign.AgentSync/ChangePassword',
            sync__pb2.ChangePasswordRequest.SerializeToString,
            sync__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ManageGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sovereign.AgentSync/ManageGroup',
            sync__pb2.ManageGroupRequest.SerializeToString,
            sync__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sovereign.AgentSync/ListUsers',
            sync__pb2.UserDirectoryRequest.SerializeToString,
            sync__pb2.UserDirectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sovereign.AgentSync/SyncUsers',
            sync__pb2.SyncUsersRequest.SerializeToString,
            sync__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProcessDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sovereign.AgentSync/GetProcessDirectory',
            sync__pb2.ProcessDirectoryRequest.SerializeToString,
            sync__pb2.ProcessDirectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPortBindings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sovereign.AgentSync/GetPortBindings',
            sync__pb2.PortBindingsRequest.SerializeToString,
            sync__pb2.PortBindingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TeleportAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sovereign.AgentSync/TeleportAgent',
            sync__pb2.TeleportRequest.SerializeToString,
            sync__pb2.TeleportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TracePedigree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sovereign.AgentSync/TracePedigree',
            sync__pb2.PedigreeRequest.SerializeToString,
            sync__pb2.PedigreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProposeSwarmMutation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sovereign.AgentSync/ProposeSwarmMutation',
            sync__pb2.MutationRequest.SerializeToString,
            sync__pb2.MutationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuerySwarmLedger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sovereign.AgentSync/QuerySwarmLedger',
            sync__pb2.LedgerQueryRequest.SerializeToString,
            sync__pb2.LedgerQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TimeTravelOverride(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sovereign.AgentSync/TimeTravelOverride',
            sync__pb2.TimeTravelRequest.SerializeToString,
            sync__pb2.TimeTravelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForensicAudit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sovereign.AgentSync/ForensicAudit',
            sync__pb2.ForensicRequest.SerializeToString,
            sync__pb2.ForensicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
